### ISSUE TITLE
Receiving ClassCastException in getGameDatumFromRow

### ISSUE THREAD

**Issue by Arijit-Basu** [linkedin/photon-ml#410]
Received the following exception while calling
```
estimator.fit(
    fixedInputData,
    Some(fixedValidateData),
    Seq(fixedCoordinateOptConfigs)).head
```
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at com.linkedin.photon.ml.data.GameConverters$.getGameDatumFromRow(GameConverters.scala:96)
	at com.linkedin.photon.ml.data.GameConverters$$anonfun$getGameDatasetFromDataFrame$2.apply(GameConverters.scala:64)
	at com.linkedin.photon.ml.data.GameConverters$$anonfun$getGameDatasetFromDataFrame$2.apply(GameConverters.scala:63)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:344)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19/02/28 20:04:21 WARN TaskSetManager: Lost task 0.0 in stage 9.0 (TID 23, localhost, executor driver): java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at com.linkedin.photon.ml.data.GameConverters$.getGameDatumFromRow(GameConverters.scala:96)
	at com.linkedin.photon.ml.data.GameConverters$$anonfun$getGameDatasetFromDataFrame$2.apply(GameConverters.scala:64)
	at com.linkedin.photon.ml.data.GameConverters$$anonfun$getGameDatasetFromDataFrame$2.apply(GameConverters.scala:63)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:344)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This is my input data format
```
{"uid": "abcd", "p_id": "efgh", "response": 0.1, "features": [{"name": "a", "value": 0.0, "term": null}, {"name": "b", "value": 0.0, "term": null}, {"name": "c", "value": 0.0, "term": null}, {"name": "d", "value": 0.0, "term": null}, {"name": "e", "value": 0.0, "term": null}, {"name": "f Nadu", "value": 0.0, "term": null}, {"name": "g", "value": 0.0, "term": null}, {"name": "h Pradesh", "value": 1.0, "term": null}, {"name": "i", "value": 1.0, "term": null}, {"name": "j", "value": 0.0, "term": null}, {"name": "k", "value": 0.0, "term": null}, {"name": "l", "value": 0.0, "term": null}, {"name": "m", "value": 0.0, "term": null}, {"name": "n", "value": 0.0, "term": null}], "metadataMap": null, "weight": null, "offset": null}
```
On investigation,  I found the following
```
row.getAs[Number](columns(InputColumnsNames.RESPONSE)).doubleValue
```
The response column is string. Is this intended?
If not is this a code or a configuration bug.

**Comment by ashelkovnykov** [comment]
@Arijit-Basu I would not consider this a bug: for logistic regression, the response should be a whole number in the range [0, 1]; for Poisson regression, the response should be a whole number; for linear regression, the response should be a real number. In all cases, the response is numeric: there is no reason to have the response field type be `String`.

**Comment by Arijit-Basu** [comment]
@ashelkovnykov I am passing the response as a Number.
```
{"uid": "abcd", "p_id": "efgh", "response": 0.1, "features": [{"name": "a", "value": 0.0, "term": null}, {"name": "b", "value": 0.0, "term": null}, {"name": "c", "value": 0.0, "term": null}, {"name": "d", "value": 0.0, "term": null}, {"name": "e", "value": 0.0, "term": null}, {"name": "f Nadu", "value": 0.0, "term": null}, {"name": "g", "value": 0.0, "term": null}, {"name": "h Pradesh", "value": 1.0, "term": null}, {"name": "i", "value": 1.0, "term": null}, {"name": "j", "value": 0.0, "term": null}, {"name": "k", "value": 0.0, "term": null}, {"name": "l", "value": 0.0, "term": null}, {"name": "m", "value": 0.0, "term": null}, {"name": "n", "value": 0.0, "term": null}], "metadataMap": null, "weight": null, "offset": null}```
This is my input.  But the response becomes string. Am I doing anything wrong?

**Comment by Arijit-Basu** [comment]
@ashelkovnykov Sorry, figured out the issue.  The problem was with my .avsc file. I had described the response field with the following json:
```
{
    "name" : "response",
    "type" : [ "double", "float", "int", "long", "boolean","string"],
    "doc" : "label/response of the event"
  }
```
and the python script was converting the float value to string.
Removing string from the type solved the issue. Thanks.

**Comment by ashelkovnykov** [comment]
Glad to hear that it's working for you now!
