### ISSUE TITLE
Getting exception while fitting the Random Effect Model

### ISSUE THREAD

**Issue by Arijit-Basu** [linkedin/photon-ml#411]
Getting this exception while calling the fit method in GameEstimator. I have run the same steps as in the tutorial. 

```Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Exception while getting task result: java.io.InvalidClassException: com.linkedin.photon.ml.optimization.SingleNodeOptimizationProblem; no valid constructor
StackTrace:   at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1575)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1563)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1562)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1562)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:803)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:803)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:803)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1790)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1745)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1734)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:619)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2029)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2050)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2069)
  at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1362)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.take(RDD.scala:1335)
  at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1376)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.first(RDD.scala:1375)
  at com.linkedin.photon.ml.optimization.game.RandomEffectOptimizationProblem.initializeModel(RandomEffectOptimizationProblem.scala:114)
  at com.linkedin.photon.ml.algorithm.RandomEffectCoordinateInProjectedSpace$.com$linkedin$photon$ml$algorithm$RandomEffectCoordinateInProjectedSpace$$initializeModel(RandomEffectCoordinateInProjectedSpace.scala:133)
  at com.linkedin.photon.ml.algorithm.RandomEffectCoordinateInProjectedSpace.initializeModel(RandomEffectCoordinateInProjectedSpace.scala:60)
  at com.linkedin.photon.ml.algorithm.RandomEffectCoordinateInProjectedSpace.initializeModel(RandomEffectCoordinateInProjectedSpace.scala:32)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$train$1$$anonfun$33$$anonfun$35.apply(GameEstimator.scala:759)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$train$1$$anonfun$33.apply(GameEstimator.scala:759)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$train$1$$anonfun$33.apply(GameEstimator.scala:755)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$train$1.apply(GameEstimator.scala:755)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$train$1.apply(GameEstimator.scala:704)
  at com.linkedin.photon.ml.util.Timed$.measureDuration(Timed.scala:71)
  at com.linkedin.photon.ml.util.Timed$.apply(Timed.scala:57)
  at com.linkedin.photon.ml.estimators.GameEstimator.train(GameEstimator.scala:704)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$12$$anonfun$apply$4.apply(GameEstimator.scala:349)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$12$$anonfun$apply$4.apply(GameEstimator.scala:348)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:285)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$12.apply(GameEstimator.scala:348)
  at com.linkedin.photon.ml.estimators.GameEstimator$$anonfun$12.apply(GameEstimator.scala:344)
  at com.linkedin.photon.ml.util.Timed$.measureDuration(Timed.scala:71)
  at com.linkedin.photon.ml.util.Timed$.apply(Timed.scala:57)
  at com.linkedin.photon.ml.estimators.GameEstimator.fit(GameEstimator.scala:344)

**Comment by Arijit-Basu** [comment]
@ashelkovnykov   https://github.com/linkedin/photon-ml/pull/412
This fixed the issue for me.

**Comment by ashelkovnykov** [comment]
@Arijit-Basu Could you please link the code that you're running which encounters this problem? None of the unit, integration, or live tests are experiencing this issue.

Regarding your linked PR #412: We don't want the `GeneralizedLinearOptimizationProblem` to be `Serializable` as we do not want all subclasses to be `Serializable`. Only the `SingleNodeOptimizationProblem` and its subclasses should be `Serializable`, and so they extend the trait.

**Comment by ashelkovnykov** [comment]
Closed due to inactivity. @Arijit-Basu Please see previous comment and re-open if necessary.
