### ISSUE TITLE
Cannot build photon-ml with Java 11

### ISSUE THREAD

**Issue by cvanhoutte** [linkedin/photon-ml#482]
Hi there

I'm trying to install on Debian10 and am following the instructions in the README, but at this command I'm coming across the following error.

Do you have any suggestions? Thanks

```
$ ./gradlew build -x test -x integTest --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.11'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.11'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:253)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

**Comment by cvanhoutte** [comment]
Hi there, still trying to get up and running with this. Unfortunately I can't try with Java 8 on Debian 10 (not supported and security issues), so now I'm trying install inside an Azure Databricks notebook that uses Databricks 8.2 (Apache Spark 3.1.1, Scala 2.12). I'm hoping in this way I can use the API similar to the tutorial described in this repo.

```
%sh git clone https://github.com/linkedin/photon-ml 
```
```
%sh ./gradlew build -x test -x integTest
```
And I receive a 'build successful' message.

However,
```
%scala
import com.linkedin.photon.ml.TaskType.LOGISTIC_REGRESSION

command-1920204351554641:7: error: object linkedin is not a member of package com
```

Apologies if this one is obvious, I've primarily used pyspark up until now.

Thanks

**Comment by cvanhoutte** [comment]
Hi there,

Last one from me if there is no response.

Is the API no longer well supported? If not, would it be possible to please update the tutorial docker image to use the CLI instead? 

There seem to be some backwards compatibility issues with getting this code up and running.

Thanks

**Comment by sadatnfs** [comment]
I tried a bunch of different things like upgrading the gradle version, and then also upgrading the Scala versions since 2.11 is so far behind now. All combos of changing leads to some build issues or the other; I think this project is abandoned
